### PR TITLE
Add Not In Combat option

### PR DESCRIPTION
**Pull request by soheilpro**

### CODE REVIEW

**Comment by Repooc** [comment]
You left no information on why this is needed. What are you trying to accomplish.

**Comment by Repooc** [comment]
BTW, you can reach out in the discord for all my plugins https://repoocreforged.dev/discord for easier back and forth conversation instead of github comments on the pr if u would rather do it that way. There is a channel for each of my plugins you can post in.

**Comment by soheilpro** [comment]
Well, I was looking for a way to hide my action bars during combat but still be able to access them when I mouse over them. By selecting the `Mouseover` and `Not In Combat` options, I can accomplish this.

I have set up WeakAuras for most of my primary actions, so I prefer my action bars hidden for less distraction. However, sometimes during a fight, I need them, and the mouseover option helps in such situations.

Thanks for the great add-on, BTW :)

**Comment by Repooc** [comment]
pull my commit and test that instead of what you have
this way, people can't select both and get confused.
I may have to put some kind of legend to signal Checked = In Combat, Greyed Checked = Not In Combat, Unchecked = Ignore Combat all together, basically the only "real" change is the grey checked which is a specific check for Not In Combat

**Comment by soheilpro** [comment]
That works perfectly!

You can also style it like WeakAuras:

Screenshot 2023-12-08 at 15 16 07
Screenshot 2023-12-08 at 15 16 13
Screenshot 2023-12-08 at 15 16 22

**Comment by soheilpro** [comment]
Unfortunately, I am not familiar with widgets and how to style them. As long as the functionality is there, I'm happy :)

Thank you!

**Comment by soheilpro** [comment]
I'm not sure if you've already fixed this, but there is currently a bug that if you choose "Not In Combat" and reload, the setting reverts back to "In Combat."

**Comment by Repooc** [comment]
No I haven't done much of anything as I'm at work or was taking a nap between jobs.  Will have to look later this afternoon

**Comment by Repooc** [comment]
Heads up, I have done a good amount of changes and you may need to reclone the repo as I added a git submodule to the repo as I will be making some other changes to the config to move some stuff around (not the options themselves)

**Pull request closed without merging**
